sonar.projectKey=LukasPietzschmann_Kyra
sonar.organization=lukaspietzschmann

sonar.projectName=Kyra

sonar.sources=.
sonar.exclusions=build/**

sonar.sourceEncoding=UTF-8

sonar.cfamily.cache.enabled=true
sonar.cfamily.cache.path=/home/runner/.sonar/cache